<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<RootNamespace>c11tester_tools</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<!--<PublishAot>true</PublishAot>-->
		<!--<InvariantGlobalization>true</InvariantGlobalization>-->
	</PropertyGroup>
	<ItemGroup>
	  <None Update="stdin.txt">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
</Project>
