# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jk/execution-log-parser

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jk/execution-log-parser

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jk/execution-log-parser/CMakeFiles /home/jk/execution-log-parser//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jk/execution-log-parser/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_execution_trace_parcing

# Build rule for target.
test_execution_trace_parcing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_execution_trace_parcing
.PHONY : test_execution_trace_parcing

# fast build rule for target.
test_execution_trace_parcing/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_execution_trace_parcing.dir/build.make CMakeFiles/test_execution_trace_parcing.dir/build
.PHONY : test_execution_trace_parcing/fast

#=============================================================================
# Target rules for targets named test_sequential_consistency

# Build rule for target.
test_sequential_consistency: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_sequential_consistency
.PHONY : test_sequential_consistency

# fast build rule for target.
test_sequential_consistency/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_sequential_consistency.dir/build.make CMakeFiles/test_sequential_consistency.dir/build
.PHONY : test_sequential_consistency/fast

graph_checker.o: graph_checker.cpp.o
.PHONY : graph_checker.o

# target to build an object file
graph_checker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_sequential_consistency.dir/build.make CMakeFiles/test_sequential_consistency.dir/graph_checker.cpp.o
.PHONY : graph_checker.cpp.o

graph_checker.i: graph_checker.cpp.i
.PHONY : graph_checker.i

# target to preprocess a source file
graph_checker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_sequential_consistency.dir/build.make CMakeFiles/test_sequential_consistency.dir/graph_checker.cpp.i
.PHONY : graph_checker.cpp.i

graph_checker.s: graph_checker.cpp.s
.PHONY : graph_checker.s

# target to generate assembly for a file
graph_checker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_sequential_consistency.dir/build.make CMakeFiles/test_sequential_consistency.dir/graph_checker.cpp.s
.PHONY : graph_checker.cpp.s

parser.o: parser.cpp.o
.PHONY : parser.o

# target to build an object file
parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_execution_trace_parcing.dir/build.make CMakeFiles/test_execution_trace_parcing.dir/parser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_sequential_consistency.dir/build.make CMakeFiles/test_sequential_consistency.dir/parser.cpp.o
.PHONY : parser.cpp.o

parser.i: parser.cpp.i
.PHONY : parser.i

# target to preprocess a source file
parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_execution_trace_parcing.dir/build.make CMakeFiles/test_execution_trace_parcing.dir/parser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_sequential_consistency.dir/build.make CMakeFiles/test_sequential_consistency.dir/parser.cpp.i
.PHONY : parser.cpp.i

parser.s: parser.cpp.s
.PHONY : parser.s

# target to generate assembly for a file
parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_execution_trace_parcing.dir/build.make CMakeFiles/test_execution_trace_parcing.dir/parser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_sequential_consistency.dir/build.make CMakeFiles/test_sequential_consistency.dir/parser.cpp.s
.PHONY : parser.cpp.s

tests/test_execution_trace_parcing.o: tests/test_execution_trace_parcing.cpp.o
.PHONY : tests/test_execution_trace_parcing.o

# target to build an object file
tests/test_execution_trace_parcing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_execution_trace_parcing.dir/build.make CMakeFiles/test_execution_trace_parcing.dir/tests/test_execution_trace_parcing.cpp.o
.PHONY : tests/test_execution_trace_parcing.cpp.o

tests/test_execution_trace_parcing.i: tests/test_execution_trace_parcing.cpp.i
.PHONY : tests/test_execution_trace_parcing.i

# target to preprocess a source file
tests/test_execution_trace_parcing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_execution_trace_parcing.dir/build.make CMakeFiles/test_execution_trace_parcing.dir/tests/test_execution_trace_parcing.cpp.i
.PHONY : tests/test_execution_trace_parcing.cpp.i

tests/test_execution_trace_parcing.s: tests/test_execution_trace_parcing.cpp.s
.PHONY : tests/test_execution_trace_parcing.s

# target to generate assembly for a file
tests/test_execution_trace_parcing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_execution_trace_parcing.dir/build.make CMakeFiles/test_execution_trace_parcing.dir/tests/test_execution_trace_parcing.cpp.s
.PHONY : tests/test_execution_trace_parcing.cpp.s

tests/test_sequential_consistency.o: tests/test_sequential_consistency.cpp.o
.PHONY : tests/test_sequential_consistency.o

# target to build an object file
tests/test_sequential_consistency.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_sequential_consistency.dir/build.make CMakeFiles/test_sequential_consistency.dir/tests/test_sequential_consistency.cpp.o
.PHONY : tests/test_sequential_consistency.cpp.o

tests/test_sequential_consistency.i: tests/test_sequential_consistency.cpp.i
.PHONY : tests/test_sequential_consistency.i

# target to preprocess a source file
tests/test_sequential_consistency.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_sequential_consistency.dir/build.make CMakeFiles/test_sequential_consistency.dir/tests/test_sequential_consistency.cpp.i
.PHONY : tests/test_sequential_consistency.cpp.i

tests/test_sequential_consistency.s: tests/test_sequential_consistency.cpp.s
.PHONY : tests/test_sequential_consistency.s

# target to generate assembly for a file
tests/test_sequential_consistency.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_sequential_consistency.dir/build.make CMakeFiles/test_sequential_consistency.dir/tests/test_sequential_consistency.cpp.s
.PHONY : tests/test_sequential_consistency.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... test_execution_trace_parcing"
	@echo "... test_sequential_consistency"
	@echo "... graph_checker.o"
	@echo "... graph_checker.i"
	@echo "... graph_checker.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... tests/test_execution_trace_parcing.o"
	@echo "... tests/test_execution_trace_parcing.i"
	@echo "... tests/test_execution_trace_parcing.s"
	@echo "... tests/test_sequential_consistency.o"
	@echo "... tests/test_sequential_consistency.i"
	@echo "... tests/test_sequential_consistency.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

